title: Praveen K Pandey
email: praveen.gbpec@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing the knowledge gained.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


github_username : PraveenPenguin
linkedin_username:  praveen-pandey-83b66919

# Build settings
markdown: kramdown
# theme: jekyll-theme-tactile
theme: minima

plugins:
  - jekyll-feed
